import assert from 'node:assert/strict';import path from 'node:path';import {write,openFolds} from './support.mjs';
export async function extraCases(page,record,out,engine){
const row=id=>page.locator('[data-export-field="'+id+'"] input'),read=()=>page.evaluate(()=>window.review.read()),update=p=>page.evaluate(p=>window.review.update(p),p);
const settle=(id,result,rejected=false)=>page.evaluate(({id,result,rejected})=>window.review.settle(id,result,rejected),{id,result,rejected});
const commands=async()=>(await read()).calls.filter(c=>c.method==='dispatch'||c.method==='exportFile');
const rejection=message=>({ok:false,diagnostic:{code:'REVIEW_REFUSAL',message,severity:'error'}});
const confirmation=id=>({...rejection(id),confirmation:{title:'Conversion '+id,changes:['Explicit conversion '+id],retry:{type:'proposal.accept',id,confirmed:true}}});
const receipt=(id,verdict='pass',inspection=false)=>({id,formatId:'captured-format-'+id,filename:'Đồ án tiếng Việt — mẫu kiểm tra — '+id+'.stl',byteLength:2097153,sha256:'0123456789abcdef'.repeat(4),projectRevision:0,createdAt:'2026-09-08T08:00:00.000Z',verdict,inspection,warnings:['Giữ nguyên cảnh báo hình học: vùng giao nhau chưa kiểm.'],metadataAvailable:true});
async function shot(id){const p=path.join(out,engine+'-'+id+'.png');await page.screenshot({path:p});return p}
async function check(id,name,fn){await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>window.review.reset());await openFolds(page);try{const observed=await fn()??{};await record({id,name,pass:true,observed})}catch(e){const observed=await read();const p=await shot(id);write(path.join(out,engine+'-'+id+'-state.json'),observed);await record({id,name,pass:false,error:String(e.stack),observed,evidence:p})}}
await check('R01','optional, empty and historical receipts preserve declared facts',async()=>{
await update({exportReceipts:undefined});assert.equal(await page.locator('[data-export-receipts]').count(),0);await update({exportReceipts:[]});assert.equal(await page.locator('[data-export-receipts="0"]').count(),1);
const records=['pass','fail','unverified','unsupported'].map((v,i)=>receipt('R'+i,v,i%2===1));await update({project:{revision:9,visibleModelRevision:0,visibleModelStale:true},exportReceipts:records});
for(const r of records){const l=page.locator('[data-export-receipt="'+r.id+'"]');assert.equal(await l.getAttribute('data-export-receipt-verdict'),r.verdict);assert.equal(await l.getAttribute('data-export-receipt-inspection'),String(r.inspection));assert.equal(await l.locator('[data-export-receipt-sha]').textContent(),r.sha256);assert.equal(await l.locator('[data-export-receipt-bytes]').getAttribute('data-export-receipt-bytes'),String(r.byteLength));assert.ok((await l.innerText()).includes('bản sửa 0'))}
assert.ok((await page.locator('[data-export-receipts]').innerText()).includes('không biết hệ điều hành đã lưu'));assert.ok((await page.locator('[data-export-config-model]').innerText()).includes('0'));await page.locator('[data-export-receipt="R0"]').scrollIntoViewIfNeeded();return {receipts:records,screenshot:await shot('R01'),accessibility:await page.locator('[data-export-receipts]').ariaSnapshot()}
});
await check('R02','receipt reordering retains download ID and metadata refusals remain reachable',async()=>{
const a=receipt('A'),b={...receipt('B'),metadataAvailable:false};await update({exportReceipts:[a,b]});await update({exportReceipts:[b,a]});const blocked=page.locator('[data-export-receipt="B"] button');await blocked.focus();await blocked.press('Enter');assert.equal((await commands()).length,0);const btn=page.locator('[data-export-receipt="A"] button');await btn.click();const c=(await commands()).at(-1);assert.deepEqual(c.input,{type:'export.receipt',id:'A'});await settle(c.id,rejection('CURRENT_METADATA_REJECTION'));assert.ok((await page.locator('[data-export-receipt="A"]').innerText()).includes('CURRENT_METADATA_REJECTION'));return {calls:await commands(),blockedDescription:await blocked.getAttribute('aria-describedby')}
});
await check('R03','removed receipt and account ABA drop late errors and confirmation bodies',async()=>{
await update({exportReceipts:[receipt('A')]});await page.locator('[data-export-receipt="A"] button').click();let c=(await commands()).at(-1);await update({exportReceipts:[]});await settle(c.id,confirmation('REMOVED_PRIVATE'));assert.ok(!JSON.stringify((await read()).state).includes('REMOVED_PRIVATE'));
await update({exportReceipts:[receipt('B')]});await page.locator('[data-export-receipt="B"] button').click();c=(await commands()).at(-1);await page.evaluate(()=>window.review.aba('account'));await settle(c.id,'REJECTED_FOREIGN_PRIVATE',true);const r=await read();assert.ok(!JSON.stringify(r.state).includes('REJECTED_FOREIGN_PRIVATE'));return {state:r.state}
});
await check('R04','renderer export identifies the stale visible model and leaves revision intact',async()=>{
const r=await read();await update({project:{revision:3,visibleModelRevision:0,visibleModelStale:true},exports:[...r.snapshot.exports,{id:'png-renderer',label:'Ảnh chụp mô hình',extension:'png',enabled:true,verdict:'unverified',prerequisite:'renderer'}]});const card=page.locator('[data-export-option="png-renderer"]');assert.ok((await card.innerText()).includes('Tệp này không phải hình của thiết kế hiện tại.'));await card.getByRole('button',{name:'Xuất để kiểm tra',exact:true}).click();const c=(await commands()).at(-1);assert.equal(c.input,'png-renderer');await settle(c.id,{ok:true});assert.equal((await read()).snapshot.project.visibleModelRevision,0);assert.equal((await read()).snapshot.project.revision,3);return {text:await card.innerText(),calls:await commands()}
});
await check('K01','keyboard config controls preserve literal values and bound errors',async()=>{
await row('filename').focus();await page.keyboard.type(' Bàn phím');await page.keyboard.press('Tab');const c=(await commands()).at(-1);assert.equal(c.input.field,'filename');await settle(c.id,rejection('KEYBOARD_VALIDATION'));const described=await row('filename').evaluate(e=>({label:e.labels?.[0]?.innerText,invalid:e.getAttribute('aria-invalid'),descriptions:(e.getAttribute('aria-describedby')??'').split(' ').map(id=>document.getElementById(id)?.textContent)}));assert.ok(described.label.includes('Tên tệp'));assert.equal(described.invalid,'true');assert.ok(described.descriptions.includes('KEYBOARD_VALIDATION'));
await row('filename').press('Escape');await row('inspection').focus();await page.keyboard.press('Space');const toggle=(await commands()).at(-1);assert.equal(toggle.input.field,'inspection');assert.equal(toggle.input.value,true);assert.equal(await row('inspection').isChecked(),false);
const select=page.locator('[data-export-field="orientation"] select');await select.focus();await select.press('ArrowDown');await select.press('Enter');const choice=(await commands()).at(-1);assert.equal(choice.input.field,'orientation');return {described,calls:await commands(),selectAccessibility:await select.ariaSnapshot()}
});
await check('K02','mobile Escape discards only the field draft before closing its drawer',async()=>{
await page.setViewportSize({width:320,height:800});await page.evaluate(()=>window.review.section('export'));await row('filename').fill('Discard only this draft');await row('filename').press('Escape');const r=await read();write(path.join(out,engine+'-K02-observed.json'),{drawerOpen:r.state.drawerOpen,shown:await row('filename').inputValue(),activeElement:await page.evaluate(()=>({tag:document.activeElement?.tagName,inert:!!document.activeElement?.closest('[inert]')}))});assert.equal(await row('filename').inputValue(),'Mô hình');assert.equal(r.state.drawerOpen,true);await row('filename').press('Escape');assert.equal((await read()).state.drawerOpen,false)
});
for(const [width,height,fontSize] of [[320,800,14],[320,800,28],[1280,900,28]])await check('V01-'+width+'-'+fontSize,'export controls and long receipts reflow at '+width+'px / '+fontSize+'px app text',async()=>{
await page.setViewportSize({width,height});const long={...receipt('LONG'),filename:'Đồ_án_'.repeat(15)+'.stl',warnings:['Cảnh_báo_'.repeat(22)]};await update({settings:[{key:'fontSize',label:'Cỡ chữ',value:String(fontSize)}],exportReceipts:[long]});await page.evaluate(()=>window.review.section('export'));await row('errorMm').fill('0,000000000000001 invalid');await row('errorMm').press('Enter');let c=(await commands()).at(-1);await settle(c.id,rejection('Giá trị thập phân không hợp lệ. Hãy giữ nguyên nội dung để sửa; không tự làm tròn.'));
const observations=[];for(const selector of ['[data-export-field="filename"]','[data-export-field="errorMm"]','[data-export-field="orientation"]','[data-export-receipt="LONG"]']){const l=page.locator(selector);await l.scrollIntoViewIfNeeded();const metrics=await l.evaluate(e=>{const p=document.querySelector('.panel__body');const pr=p.getBoundingClientRect(),r=e.getBoundingClientRect();const bad=[e,...e.querySelectorAll('*')].filter(n=>n.getClientRects().length&&!n.classList.contains('u-visually-hidden')).map(n=>({tag:n.tagName,cls:n.className,text:n.textContent?.slice(0,120),left:n.getBoundingClientRect().left,right:n.getBoundingClientRect().right,client:n.clientWidth,scroll:n.scrollWidth})).filter(n=>n.left<pr.left-2||n.right>pr.right+2);return {panel:{left:pr.left,right:pr.right,client:p.clientWidth,scroll:p.scrollWidth},row:{left:r.left,right:r.right,width:r.width},bad,viewport:innerWidth,scale:devicePixelRatio}});observations.push({selector,metrics,screenshot:await shot('V01-'+width+'-'+fontSize+'-'+observations.length)})}
write(path.join(out,engine+'-V01-'+width+'-'+fontSize+'-metrics.json'),observations);assert.ok(observations.every(o=>o.metrics.bad.length===0),'Content crosses panel boundaries');return {observations}
});
await check('K03','published disabled controls have a keyboard-reachable reason',async()=>{
const s=(await read()).snapshot;await update({exports:s.exports.map(o=>({...o,configuration:{...o.configuration,fields:o.configuration.fields.map(f=>({...f,enabled:false,reason:'LOCK_REASON_'+f.id}))}}))});const select=page.locator('[data-export-field="orientation"] select'),check=row('inspection');const states=await page.locator('[data-export-field]').evaluateAll(rows=>rows.map(r=>{const i=r.querySelector('input,select');return {id:r.getAttribute('data-export-field'),disabled:i.disabled,readOnly:i.readOnly,tabIndex:i.tabIndex,description:i.getAttribute('aria-describedby'),focusableReason:[...r.querySelectorAll('[tabindex],button,a,input,select')].some(e=>!e.disabled&&(e.tabIndex>=0))}}));write(path.join(out,engine+'-K03-focus.json'),states);assert.ok(states.every(r=>r.focusableReason),'Disabled choice fields remove the only focus target for their reason');return {states}
});
await check('K04','numeric limits and unit are associated with the input for assistive reading',async()=>{
const s=(await read()).snapshot;await update({exports:s.exports.map(o=>({...o,configuration:{...o.configuration,fields:o.configuration.fields.map(f=>f.id==='errorMm'?{...f,hint:undefined}:f)}}))});const details=await row('errorMm').evaluate(e=>({name:[...e.labels].map(l=>l.textContent).join(' '),description:(e.getAttribute('aria-describedby')??'').split(' ').filter(Boolean).map(id=>document.getElementById(id)?.textContent).join(' '),ariaMin:e.getAttribute('aria-valuemin'),ariaMax:e.getAttribute('aria-valuemax')}));write(path.join(out,engine+'-K04-name.json'),details);assert.ok(details.description.includes('mm')&&details.description.includes('0.000001')&&details.description.includes('1'),'Published range and unit are not in the accessible description');return {details}
});
}

