import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
export const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
export function safe(root,p){root=fs.realpathSync(root);p=path.resolve(p);if(p!==root&&!p.startsWith(root+path.sep))throw Error('Output outside run');for(let a=p;a!==root;a=path.dirname(a))if(fs.existsSync(a)&&fs.lstatSync(a).isSymbolicLink())throw Error('Reparse input/output');return p;}
let captured;
export function env(){if(captured)return captured;const repo=fs.realpathSync(process.env.PROJECT_ROOT),run=safe(repo,process.env.PROJECT_REVIEW_RUN);if(!/^tmp\/reviews\/(codex|opus)\/runs\/[a-zA-Z0-9_-]+$/.test(path.relative(repo,run).replaceAll('\\','/')))throw Error('Explicit project run required');const snapshot=safe(run,path.join(run,'inputs/source')),stage=safe(run,path.join(run,'work/h')),manifestFile=safe(run,path.join(run,'inputs/source-manifest.json')),files=[];
function copy(dir,relative,out){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=safe(repo,path.join(dir,e.name)),rel=path.join(relative,e.name);if(e.isDirectory())copy(p,rel,out);else{if(!e.isFile())throw Error('Regular source required');const b=fs.readFileSync(p),dest=safe(run,path.join(out,rel));fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,b);files.push({path:path.relative(repo,p).replaceAll('\\','/'),capturedPath:path.relative(run,dest).replaceAll('\\','/'),bytes:b.length,sha256:sha(b)});}}}
if(fs.existsSync(manifestFile))throw Error('Use a fresh run; source capture is immutable');for(const rel of['src/ui','src/contracts'])copy(path.join(repo,rel),rel,snapshot);copy(import.meta.dirname,'',stage);files.sort((a,b)=>a.path.localeCompare(b.path));const b=Buffer.from(JSON.stringify({version:'arch-ui-consent-input/1',at:new Date().toISOString(),files},null,2)+'\n');fs.writeFileSync(manifestFile,b,{flag:'wx'});captured={repo,run,snapshot,stage,manifest:{files},manifestHash:sha(b)};return captured;}
export function write(p,v){const {run}=env();safe(run,p);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');}
export function verify(){const {run,manifest}=env();for(const f of manifest.files){const b=fs.readFileSync(safe(run,path.join(run,f.capturedPath)));if(b.length!==f.bytes||sha(b)!==f.sha256)throw Error('Captured input changed: '+f.path);}write(path.join(run,'evidence/source-integrity.json'),{pass:true,files:manifest.files.length,sourceManifestHash:env().manifestHash});}
/** The export panel folds per-format settings, the printer group and an empty receipts list by default (round 2); the cases address the fields directly, so every fold is opened first. */
export async function openFolds(page){for(let i=0;i<8;i++){const heads=page.locator('.group__head[aria-expanded="false"]');if(await heads.count()===0)return;await heads.first().click();}}
