import assert from 'node:assert/strict';
const failure=(marker,confirm=false)=>({ok:false,diagnostic:{code:'TEST_REFUSAL',severity:'error',message:marker,detail:marker+'_DETAIL'},...(confirm?{confirmation:{title:marker+'_TITLE',changes:[marker+'_CHANGE'],retry:{type:'project.delete',id:marker+'_RETRY',confirmed:true}}}:{})});
const quote=marker=>({ok:true,quote:{jobId:marker,quoteHash:marker+'_HASH',providerLabel:marker+'_PROVIDER',credentialLabel:'Synthetic no-charge',recipient:'https://provider.invalid/no-network',dataToSend:[marker+'_DATA'],currency:'USD',maximumCost:'0',expiresAt:Date.now()+3600000,unknowns:[]}});
export async function browserCases(page,record){
 const read=()=>page.evaluate(()=>window.boundary.read());
 const click=id=>page.evaluate(id=>window.boundary.click(`[data-testid="${id}"]`),id);
 const button=async name=>{await page.getByRole('button',{name,exact:true}).evaluate(e=>e.setAttribute('data-test-action','true'));try{await page.evaluate(()=>window.boundary.click('[data-test-action]'))}finally{await page.locator('[data-test-action]').evaluateAll(es=>es.forEach(e=>e.removeAttribute('data-test-action')))}};
 const settle=(id,v,rejected=false)=>page.evaluate(([i,v,r])=>window.boundary.settle(i,v,r),[id,v,rejected]);
 const last=async method=>{const c=(await read()).calls.filter(c=>c.method===method).at(-1);assert.ok(c?.pending,`Expected held ${method}`);return c.id};
 const absent=async(marker,code)=>{const s=await read();assert.ok(!JSON.stringify(s.state).includes(marker),'retired payload leaked into UiState: '+marker);assert.ok(!s.html.includes(marker),'retired payload rendered: '+marker);assert.equal(s.state.toasts.length,0);assert.equal(s.state.dialogs.filter(d=>d.spec.kind==='confirm').length,0);if(code)assert.ok(s.state.log.some(l=>l.code===code),'missing bounded dropped-answer log '+code);return s};
 const check=async(name,fn)=>{await page.evaluate(()=>window.boundary.reset());try{await fn();record({name,pass:true})}catch(e){record({name,pass:false,error:e.stack,observed:await read()})}};
 const ai=async()=>{await click('ai');await page.evaluate(()=>window.boundary.input('textarea','Mẫu | có :: dấu và tiếng Việt'));assert.equal(await page.getByRole('dialog',{name:'Tạo ảnh bằng AI',exact:true}).count(),1)};
 const reference=async bytes=>{await button('Chọn ảnh tham chiếu');await page.evaluate(b=>window.boundary.file(b),bytes)};
 const noSubmit=async()=>assert.equal((await read()).calls.filter(c=>c.method==='submitImage').length,0,'Test must never submit to a provider');

 await check('current matching diagnostic renders log, toast and alert',async()=>{await click('raw');await settle(await last('importFile'),failure('CURRENT_ERROR'));const s=await read();assert.equal(s.state.log.length,1);assert.equal(s.state.log[0].detail,'CURRENT_ERROR_DETAIL');assert.equal(s.state.alert,'CURRENT_ERROR');assert.equal(s.state.toasts.length,1);assert.ok((await page.locator('[role=alert]').allTextContents()).join(' ').includes('CURRENT_ERROR'))});
 await check('current unexpected rejection remains visible, pending clears',async()=>{await click('raw');await settle(await last('importFile'),'CURRENT_REJECTION',true);const s=await read();assert.equal(s.state.log[0].code,'BRIDGE_CALL_REJECTED');assert.equal(s.state.log[0].detail,'CURRENT_REJECTION');assert.equal(await page.locator('[data-testid=raw]').getAttribute('aria-busy'),'false');assert.ok(s.html.includes('CURRENT_REJECTION'))});
 await check('current confirmation renders actual ConfirmDialog without duplicate toast',async()=>{await click('raw');await settle(await last('importFile'),failure('CURRENT_CONFIRM',true));const s=await read();assert.equal(s.state.toasts.length,0);assert.equal(s.state.log.length,1);assert.equal(s.state.dialogs.length,1);assert.ok((await page.getByRole('dialog',{name:'CURRENT_CONFIRM_TITLE',exact:true}).innerText()).includes('CURRENT_CONFIRM_CHANGE'));assert.equal(s.calls.length,1,'Displaying consent must not retry command')});
 await check('busy ref prevents duplicate handler dispatch',async()=>{await click('raw');await click('raw');assert.equal((await read()).calls.length,1);await settle(1,{ok:true});const s=await read();assert.equal(s.state.log.length,1);assert.equal(s.state.toasts[0].text,'CURRENT_SUCCESS');assert.equal(s.state.announcement,'CURRENT_ANNOUNCEMENT')});
 for(const [move,code] of [['account-aba','ANSWER_FOR_OTHER_CONTEXT'],['project-aba','ANSWER_SUPERSEDED'],['unmount','ANSWER_SUPERSEDED'],['retire','ANSWER_FOR_OTHER_CONTEXT']])for(const mode of ['confirmation','rejection','success']){
  await check(`${move}: late ${mode} cannot publish`,async()=>{await click('raw');const id=await last('importFile'),before=await read();await click(move);const after=await read();if(move.endsWith('aba')){assert.equal(after.notifications.length,2);assert.ok(after.context.project>before.context.project);assert.ok(after.commits.every(x=>JSON.parse(x)[0]==='A'&&JSON.parse(x)[1]==='P1'),'Intermediate identity committed despite one event batch')}
   if(mode==='rejection')await settle(id,'PRIVATE_REJECT',true);else await settle(id,mode==='success'?{ok:true}:failure('PRIVATE_CONFIRM',true));await absent(mode==='success'?'CURRENT_SUCCESS':mode==='rejection'?'PRIVATE_REJECT':'PRIVATE_CONFIRM',code);if(move==='retire')assert.equal((await read()).listeners,0)});
 }
 await check('ordinary project edit keeps current result owned',async()=>{await click('raw');await click('revision');await settle(await last('importFile'),failure('REVISION_ERROR'));assert.equal((await read()).state.log[0].text,'REVISION_ERROR')});
 await check('requestKey collision witness changes real hook ownership',async()=>{await click('project-key');await click('project-key-change');await settle(await last('queryFonts'),[{id:'PRIVATE_KEY_RESULT',label:'private',family:'private',style:'private'}]);await absent('PRIVATE_KEY_RESULT','ANSWER_SUPERSEDED');assert.equal(await page.locator('[data-testid=project-key-answer]').innerText(),'')});
 await check('newer serial wins reverse completion order',async()=>{await click('project-key');const a=await last('queryFonts');await click('project-key');const b=await last('queryFonts');await settle(b,[{id:'CURRENT_KEY',label:'current',family:'test',style:'normal'}]);await settle(a,[{id:'PRIVATE_SERIAL',label:'private',family:'test',style:'normal'}]);await absent('PRIVATE_SERIAL','ANSWER_SUPERSEDED');assert.ok((await page.locator('[data-testid=project-key-answer]').innerText()).includes('CURRENT_KEY'))});
 await check('project owner rejects P1 P2 P1, account owner survives project-only navigation',async()=>{await click('project-key');const p=await last('queryFonts');await click('account-key');const a=await last('queryFonts');await click('project-aba');await settle(p,[{id:'PRIVATE_PROJECT'}]);await settle(a,[{id:'CURRENT_ACCOUNT'}]);await absent('PRIVATE_PROJECT','ANSWER_FOR_OTHER_CONTEXT');assert.ok((await page.locator('[data-testid=account-key-answer]').innerText()).includes('CURRENT_ACCOUNT'))});
 await check('account owner also rejects A B A after identical final key',async()=>{await click('account-key');await click('account-aba');await settle(await last('queryFonts'),[{id:'PRIVATE_ACCOUNT'}]);await absent('PRIVATE_ACCOUNT','ANSWER_FOR_OTHER_CONTEXT')});
 await check('latest navigation owns result after changing its own project',async()=>{await click('nav1');const first=await last('dispatch');await click('nav2');const next=await last('dispatch');await page.evaluate(()=>window.boundary.changeProject('P3'));await settle(next,{ok:true});await settle(first,failure('PRIVATE_NAV',true));const s=await read();assert.ok(s.state.log.some(l=>l.text==='NAV2_SUCCESS'));assert.ok(s.state.log.some(l=>l.code==='ANSWER_SUPERSEDED'));assert.ok(!JSON.stringify(s.state).includes('PRIVATE_NAV'));assert.equal(s.state.dialogs.length,0);assert.equal(s.state.toasts.length,1)});
 await check('latest navigation genuine refusal remains visible',async()=>{await click('nav1');await settle(await last('dispatch'),failure('CURRENT_NAV_ERROR'));assert.equal((await read()).state.log[0].text,'CURRENT_NAV_ERROR')});
 for(const move of ['account-aba','retire'])await check(`navigation ${move} prevents late confirmation`,async()=>{await click('nav1');await click(move);await settle(await last('dispatch'),failure('PRIVATE_NAV_CONTEXT',true));await absent('PRIVATE_NAV_CONTEXT','ANSWER_FOR_OTHER_CONTEXT')});
 await check('unmounted navigation caller cannot publish later confirmation',async()=>{await click('nav-delete');await click('unmount');await settle(await last('dispatch'),failure('PRIVATE_NAV_UNMOUNT',true));await absent('PRIVATE_NAV_UNMOUNT','ANSWER_SUPERSEDED')});
 await check('non-context command rejects project ABA',async()=>{await click('save');await click('project-aba');await settle(await last('dispatch'),failure('PRIVATE_SAVE',true));await absent('PRIVATE_SAVE','ANSWER_SUPERSEDED')});
 await check('actual AI dialog accepts unchanged same File quote without submission',async()=>{await ai();await reference([1,2]);await button('Lấy báo giá');const id=await last('prepareImage');assert.deepEqual((await page.evaluate(id=>window.boundary.referenceBytes(id),id)).bytes,[1,2]);await settle(id,quote('CURRENT_QUOTE'));assert.equal(await page.locator('[data-ai-quote=live]').count(),1);assert.ok((await page.getByRole('dialog',{name:'Tạo ảnh bằng AI',exact:true}).innerText()).includes('CURRENT_QUOTE_PROVIDER'));await noSubmit()});
 await check('actual AI dialog rejects equal-metadata different-byte File quote',async()=>{await ai();await reference([1,2]);await button('Lấy báo giá');const id=await last('prepareImage'),old=await page.evaluate(id=>window.boundary.referenceBytes(id),id);await reference([3,4]);await settle(id,quote('PRIVATE_FILE_QUOTE'));await absent('PRIVATE_FILE_QUOTE','ANSWER_SUPERSEDED');assert.equal(await page.locator('[data-ai-quote=live]').count(),0);await button('Lấy báo giá');const newer=await page.evaluate(id=>window.boundary.referenceBytes(id),await last('prepareImage'));assert.deepEqual({...old,bytes:undefined},{...newer,bytes:undefined});assert.notDeepEqual(old.bytes,newer.bytes);await settle(await last('prepareImage'),quote('CURRENT_NEW_FILE'));assert.equal(await page.locator('[data-ai-quote=live]').count(),1);await noSubmit()});
 await check('actual AI close then late confirmation neither reopens nor leaks',async()=>{await ai();await button('Lấy báo giá');const id=await last('prepareImage');await button('Đóng');await settle(id,failure('PRIVATE_CLOSED_AI',true));await absent('PRIVATE_CLOSED_AI','ANSWER_SUPERSEDED');assert.equal(await page.getByRole('dialog').count(),0)});
 await check('actual AI close then unexpected rejection remains private',async()=>{await ai();await button('Lấy báo giá');const id=await last('prepareImage');await button('Đóng');await settle(id,'PRIVATE_CLOSED_REJECT',true);await absent('PRIVATE_CLOSED_REJECT','ANSWER_SUPERSEDED')});
 await check('actual AI account ABA rejects quote even when dialog remains mounted',async()=>{await ai();await button('Lấy báo giá');await click('account-aba');await settle(await last('prepareImage'),quote('PRIVATE_ACCOUNT_QUOTE'));await absent('PRIVATE_ACCOUNT_QUOTE','ANSWER_FOR_OTHER_CONTEXT');assert.equal(await page.locator('[data-ai-quote=live]').count(),0)});
 await check('actual AI changed prompt cannot publish old rejected body',async()=>{await ai();await button('Lấy báo giá');await page.evaluate(()=>window.boundary.input('textarea','A new | prompt :: content'));await settle(await last('prepareImage'),'PRIVATE_EDITED_REJECTION',true);await absent('PRIVATE_EDITED_REJECTION','ANSWER_SUPERSEDED')});
 await check('child passive request starts after global layout subscription',async()=>{await click('passive');assert.equal((await read()).context.active,true);await click('account-aba');await settle(await last('exportFile'),failure('PRIVATE_PASSIVE',true));await absent('PRIVATE_PASSIVE','ANSWER_FOR_OTHER_CONTEXT')});
 await check('wrapped current navigation failure is handled only once',async()=>{await click('wrapped-P2');await settle(await last('dispatch'),failure('CURRENT_WRAPPED',true));const s=await read();assert.equal(s.state.log.length,1);assert.equal(s.state.dialogs.length,1);assert.equal(s.state.dialogs[0].spec.title,'CURRENT_WRAPPED_TITLE')});
 await check('wrapped earlier navigation rejection cannot publish after newer navigation',async()=>{await click('wrapped-P2');const old=await last('dispatch');await click('wrapped-P3');await settle(await last('dispatch'),{ok:true});await settle(old,'PRIVATE_OLDER_NAV_REJECTION',true);await absent('PRIVATE_OLDER_NAV_REJECTION','ANSWER_SUPERSEDED')});
 await check('actual AI current matching unexpected rejection stays visible',async()=>{await ai();await button('Lấy báo giá');await settle(await last('prepareImage'),'CURRENT_AI_REJECTION',true);const s=await read();assert.equal(s.state.log[0].detail,'CURRENT_AI_REJECTION');assert.equal(s.state.toasts.length,1)});
 await check('actual AI changed prompt drops returned confirmation',async()=>{await ai();await button('Lấy báo giá');await page.evaluate(()=>window.boundary.input('textarea','New request text'));await settle(await last('prepareImage'),failure('PRIVATE_PROMPT_CONFIRM',true));await absent('PRIVATE_PROMPT_CONFIRM','ANSWER_SUPERSEDED')});
 for(const mode of ['quote','confirmation','rejection'])await check(`actual AI input A B A retires prior ${mode} with identical final key`,async()=>{
  await ai();const original=await page.locator('textarea').inputValue();await button('Lấy báo giá');const id=await last('prepareImage');
  await page.evaluate(a=>window.boundary.inputSequence('textarea',['B: temporarily different request',a]),original);
  assert.equal(await page.locator('textarea').inputValue(),original,'Input must finish at its exact original value');
  if(mode==='rejection')await settle(id,'PRIVATE_INPUT_ABA',true);else await settle(id,mode==='quote'?quote('PRIVATE_INPUT_ABA'):failure('PRIVATE_INPUT_ABA',true));
  await absent('PRIVATE_INPUT_ABA','ANSWER_SUPERSEDED');assert.equal(await page.locator('[data-ai-quote=live]').count(),0);await noSubmit();
 });
 await page.evaluate(()=>window.boundary.dispose());
}


