import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import {fileURLToPath,pathToFileURL} from 'node:url';import {auditChain,distance2} from './chain-oracle.mjs';
const run=fs.realpathSync(process.env.PROJECT_REVIEW_RUN),root=fs.realpathSync(process.env.PROJECT_ROOT),target=process.argv[2]??'native',dir=path.dirname(fileURLToPath(import.meta.url)),out=path.join(run,'evidence','guard-'+target+'-'+(process.argv[3]??'r1'));assert.ok(!fs.existsSync(out),'fresh guard evidence');fs.mkdirSync(out);
const {readProductSemantics}=await import(pathToFileURL(path.join(root,'src/core/product-operations.mjs')));
function invoke(name,args,expected=0){const b=path.join(run,'work/build-domain-canonical-'+target,target==='native'?'Release':'',name+(target==='native'?'.exe':'.js'));const r=spawnSync(target==='native'?b:process.execPath,target==='native'?args:[b,...args],{encoding:'utf8',timeout:90000,env:process.env});assert.equal(r.status,expected,r.error?.message??r.stderr);return r;}
let seed=0x53092026;const rand=()=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return seed>>>0;};
const rings=[[[0,0],[100,0],[0,1],[0,1000],[-1000,1000],[-1000,0]]];
for(let k=0;k<64;k++){const n=64+rand()%64,rx=250+rand()%500,ry=200+rand()%600,tx=k%4===0?9999000000:-(rand()%1000000),ty=k%5===0?-9999000000:rand()%1000000;const p=Array.from({length:n},(_,i)=>{const t=2*Math.PI*i/n;return [Math.round(rx*Math.cos(t))+tx,Math.round(ry*Math.sin(t))+ty];});if(k%2)p.reverse();assert.equal(new Set(p.map(v=>v.join(','))).size,p.length);rings.push(p);}
const file=path.join(out,'seed-53092026.paths');fs.writeFileSync(file,rings.length+'\n'+rings.map(p=>p.length+'\n'+p.map(v=>v.join(' ')).join('\n')).join('\n'));
const result=path.join(out,'predicate-results.json');invoke('support_paths',[file,result,'6400000']);const data=JSON.parse(fs.readFileSync(result));const proofs=data.rings.map((r,i)=>({index:i,before:auditChain(r.original,r.proposal),after:auditChain(r.original,r.result,2),refinements:r.refinements}));
assert.ok(proofs[0].before.maxGrid>2,'finite chord backtracking regression must be exercised');assert.ok(proofs[0].refinements>0);for(let i=0;i<data.rings.length;i++)assert.ok(proofs[i].after.maxGrid<=data.rings[i].boundGrid);
const fixture=path.join(dir,'fixtures'),source=path.join(fixture,'bevietnampro-nfd.arch'),wire=path.join(fixture,'bevietnampro-nfd.aprq'),prefix=path.join(out,'cancel-then-valid');invoke('replay_candidate',[source,wire,prefix,'cancel-support']);const cancel=JSON.parse(fs.readFileSync(prefix+'.cancel.json'));assert.ok(cancel.observedDuringSupport&&cancel.inputsPreserved&&!cancel.mesh);assert.ok(fs.existsSync(prefix+'.arch'));assert.equal(readProductSemantics(fs.readFileSync(prefix+'.apms')).sourceVerdict,0);
const bad=fs.readFileSync(source);const points=bad.readUInt32LE(60),contours=bad.readUInt32LE(64),indices=bad.readUInt32LE(68),from=bad.readUInt32LE(contours),a=bad.readUInt32LE(indices+4*from),b=bad.readUInt32LE(indices+4*(from+1));bad.writeBigInt64LE(bad.readBigInt64LE(points+16*a)+1n,points+16*b);bad.writeBigInt64LE(bad.readBigInt64LE(points+16*a+8),points+16*b+8);const badFile=path.join(out,'raw-one-grid-edge-input.arch');fs.writeFileSync(badFile,bad);const bp=path.join(out,'raw-one-grid-edge');invoke('replay_candidate',[badFile,wire,bp]);const bs=readProductSemantics(fs.readFileSync(bp+'.apms'));assert.ok(bs.exportBlocked&&!fs.existsSync(bp+'.arch'));assert.equal(bs.sourceDiagnostics.at(-1).message,'RAW_EDGE_UNDER_TWO_GRID_UNITS');assert.equal(bs.tables.get(21).count,0);
fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify({target,seed:'0x53092026',predicateCases:proofs.length,scope:'predicate/vertex-filter tests, not 65 product feature passes',work:data.work,proofs,cancellation:cancel,retrySourceVerdict:0,rawEdgeRefusal:bs.sourceDiagnostics.at(-1)},null,2));console.log(JSON.stringify({target,predicateCases:proofs.length,cancellation:'pass',retry:'pass',rawEdge:'refused'}));
