import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL,fileURLToPath} from 'node:url';import {area2} from './chain-oracle.mjs';import {createHash} from 'node:crypto';
const run=fs.realpathSync(process.env.PROJECT_REVIEW_RUN),root=fs.realpathSync(process.env.PROJECT_ROOT),dir=path.dirname(fileURLToPath(import.meta.url)),target=process.argv[2]??'native',phase=process.argv[3]??'r1',out=path.join(run,'evidence',`domain-${target}-${phase}`);
const {readProductSemantics}=await import(pathToFileURL(path.join(root,'src/core/product-operations.mjs')));const {readSnapshot,inspectMesh}=await import(pathToFileURL(path.join(root,'tests/oracles/mesh-oracle.mjs')));const {partMesh,bbox,inside}=await import(pathToFileURL(path.join(root,'src/kernel/source-assembly/tests/oracles/spatial-oracle.mjs')));
const source=readSnapshot(fs.readFileSync(path.join(dir,'fixtures/bevietnampro-nfd.arch'))),xy=source.points.map(p=>p.map(Number));const min=[0,1].map(a=>Math.min(...xy.map(p=>p[a]))/1e6),max=[0,1].map(a=>Math.max(...xy.map(p=>p[a]))/1e6),center=min.map((v,i)=>(v+max[i])/2);
const near=(a,b,e=1e-8)=>assert.ok(Math.abs(a-b)<=e,`${a} vs ${b} (limit ${e})`);
function even(x){const f=Math.floor(x),r=x-f;return r<.5?f:r>.5?f+1:f%2?f+1:f;}
function signature(r){let p=r.map(v=>v.map(BigInt));let changed=true;while(changed&&p.length>3){changed=false;p=p.filter((b,i)=>{const a=p[(i+p.length-1)%p.length],c=p[(i+1)%p.length],u=b.map((v,k)=>v-a[k]),v=c.map((x,k)=>x-b[k]);if(u[0]*v[1]===u[1]*v[0]&&u[0]*v[0]+u[1]*v[1]>=0n){changed=true;return false;}return true;});}const keys=p.map(a=>a.join(','));let at=0;for(let i=1;i<keys.length;i++)if(keys[i]<keys[at])at=i;return [...keys.slice(at),...keys.slice(0,at)].join(';');}
function contains(rings,p){let winding=0;for(const ring of rings)for(let i=0;i<ring.length;i++){const a=ring[i],b=ring[(i+1)%ring.length],cross=(b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0]);if(a[1]<=p[1]&&b[1]>p[1]&&cross>0)winding++;if(a[1]>p[1]&&b[1]<=p[1]&&cross<0)winding--;}return winding!==0;}
function witness(ring,all,solid){const lo=[0,1].map(i=>Math.min(...ring.map(p=>p[i]))),hi=[0,1].map(i=>Math.max(...ring.map(p=>p[i])));for(let y=1;y<24;y++)for(let x=1;x<24;x++){const p=[lo[0]+(hi[0]-lo[0])*x/24,lo[1]+(hi[1]-lo[1])*y/24];if(contains([ring],p)&&contains(all,p)===solid)return p.map(v=>v/1e6);}throw Error('No independent ring witness');}
const rows=JSON.parse(fs.readFileSync(path.join(out,'models.json'))),proof=[];
for(const row of rows.filter(r=>!r.blocked)){
 const sem=readProductSemantics(fs.readFileSync(path.join(out,row.id+'.apms'))),scene=readSnapshot(fs.readFileSync(path.join(out,row.id+'.arch'))),params=new Map(sem.parameters.map(p=>[p.field,p.value])),size=params.get('size'),scale=size/Math.max(...max.map((v,i)=>v-min[i]));near(sem.sourceTransform[0],scale,1e-14);near(sem.sourceTransform[4],-center[0]*scale,1e-13);near(sem.sourceTransform[5],-center[1]*scale,1e-13);
 const bytes=Buffer.from(sem.bytes),pt=sem.tables.get(25),rt=sem.tables.get(24),st=sem.tables.get(21);
 const preparedPoints=Array.from({length:pt.count},(_,i)=>[bytes.readBigInt64LE(pt.offset+i*pt.stride),bytes.readBigInt64LE(pt.offset+i*pt.stride+8)]);
 const preparedRings=Array.from({length:rt.count},(_,i)=>{const at=rt.offset+i*rt.stride;return preparedPoints.slice(bytes.readUInt32LE(at),bytes.readUInt32LE(at)+bytes.readUInt32LE(at+4));});
 const slabs=Array.from({length:st.count},(_,i)=>{const at=st.offset+i*st.stride;return {rings:preparedRings.slice(bytes.readUInt32LE(at),bytes.readUInt32LE(at)+bytes.readUInt32LE(at+4)),rgba:bytes.readUInt32LE(at+16),slot:bytes.readUInt32LE(at+20),role:bytes.readUInt32LE(at+28),z0:bytes.readDoubleLE(at+32),z1:bytes.readDoubleLE(at+40),id:bytes.readBigUInt64LE(at+48).toString()};});
 const originalText='Vie\u0323\u0302t Nam';assert.equal(sem.provenance.rawHash,createHash('sha256').update(originalText).digest('hex'),'original NFD raw SHA survives');assert.notEqual(sem.provenance.rawHash,createHash('sha256').update(originalText.normalize('NFC')).digest('hex'));let rings=0,holes=0,components=0,maxVolumeDelta=0;
 const meshes=scene.parts.map(p=>partMesh(scene,p));
 for(let index=0;index<source.parts.length;index++){
  const input=sem.inputRegions[index],p=source.parts[index],expected=source.contours.slice(p.contourStart,p.contourStart+p.contourCount).map(c=>c.ring.map(i=>xy[i].map((v,a)=>even((v/1e6-center[a])*scale*1e6))));
  const slabids=sem.lineage.filter(l=>l.sourceId===input.semanticId).map(l=>l.slabId),art=slabs.filter(s=>s.role===1&&slabids.includes(s.id));assert.equal(art.length,1);const slab=art[0];assert.deepEqual(slab.rings.map(signature).sort(),expected.map(signature).sort(),'all shaped outer/hole boundaries exact after declared scale/grid');assert.equal(slab.slot,input.material.slot);assert.equal(slab.rgba,input.material.rgba);
  const idx=sem.parts.findIndex(p=>p.sourceId===slab.id);assert.ok(idx>=0);assert.equal(scene.parts[idx].color,input.material.rgba);const mesh=meshes[idx],actual=inspectMesh(mesh),box=bbox(mesh),h=slab.z1-slab.z0;assert.ok(h>0);near(box.min[2],slab.z0);near(box.max[2],slab.z1);
  const area=Number(expected.reduce((v,r)=>v+area2(r),0n))/2e12;assert.ok(area>0);const perimeter=expected.reduce((sum,r)=>sum+r.reduce((v,a,i)=>{const b=r[(i+1)%r.length];return v+Math.hypot(a[0]-b[0],a[1]-b[1])/1e6;},0),0),delta=Math.abs(actual.volume-area*h);near(actual.volume,area*h,perimeter*h*1e-6+1e-9);maxVolumeDelta=Math.max(maxVolumeDelta,delta);
  for(const ring of expected){const solid=area2(ring)>0n,point=witness(ring,expected,solid);assert.equal(inside(mesh,[...point,(slab.z0+slab.z1)/2]),solid,'final mesh source contour/hole probe');rings++;if(solid)components++;else holes++;}
 }
 assert.equal(rings,12);assert.equal(holes,2);assert.equal(components,10);const bodyIndex=sem.parts.findIndex(p=>p.role===0&&p.id.startsWith('source:slab:'));assert.ok(bodyIndex>=0);const box=bbox(meshes[bodyIndex]);const budget=sem.sourceErrors.find(e=>e.stage===100).signedMaxMm;near(box.size[0],size+2*params.get('offset'),2*budget);near(box.size[1],(max[1]-min[1])*scale+2*params.get('offset'),2*budget);
 proof.push({id:row.id,exactRings:rings,holeProbes:holes,disconnectedSolidProbes:components,maxVolumeDelta,nominalSizeMm:size,sourceScale:scale});
}
fs.writeFileSync(path.join(out,'preservation.json'),JSON.stringify({target,proof},null,2));console.log(JSON.stringify({target,models:proof.length,rings:proof.reduce((v,p)=>v+p.exactRings,0),holes:proof.reduce((v,p)=>v+p.holeProbes,0),maxVolumeDelta:Math.max(...proof.map(p=>p.maxVolumeDelta))}));
