import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import {fileURLToPath,pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';import {auditChain} from './chain-oracle.mjs';
const run=fs.realpathSync(process.env.PROJECT_REVIEW_RUN),root=fs.realpathSync(process.env.PROJECT_ROOT),testdir=path.dirname(fileURLToPath(import.meta.url)),target=process.argv[2]??'native',phase=process.argv[3]??'r1';assert.match(phase,/^[a-z0-9-]+$/);assert.ok(['native','wasm'].includes(target));
const out=path.join(run,'evidence','domain-'+target+'-'+phase);assert.ok(!fs.existsSync(out),'fresh evidence phase');fs.mkdirSync(out);const fixture=path.join(testdir,'fixtures');
const {readProductSemantics}=await import(pathToFileURL(path.join(root,'src/core/product-operations.mjs')));
const {readSnapshot,inspectMesh}=await import(pathToFileURL(path.join(root,'tests/oracles/mesh-oracle.mjs')));
const {partMesh,bbox,inside,intersections}=await import(pathToFileURL(path.join(root,'src/kernel/source-assembly/tests/oracles/spatial-oracle.mjs')));
const sha=b=>createHash('sha256').update(b).digest('hex'),rows=[];
function invoke(name,args,expected=0){const b=path.join(run,'work/build-domain-canonical-'+target,target==='native'?'Release':'',name+(target==='native'?'.exe':'.js'));const r=spawnSync(target==='native'?b:process.execPath,target==='native'?args:[b,...args],{encoding:'utf8',timeout:90000,env:process.env});assert.equal(r.status,expected,r.error?.message??r.stderr);return r;}
const source=path.join(fixture,'bevietnampro-nfd.arch'),base=fs.readFileSync(path.join(fixture,'bevietnampro-nfd.aprq'));
function set(w,id,value){const count=w.readUInt32LE(16);for(let i=0;i<count;i++){const at=256+i*40;if(w.readUInt32LE(at)===id){w.writeDoubleLE(value,at+24);return;}}throw Error('missing param '+id);}
const cases=[{id:'default-noi'},{id:'size36-tol0005',size:36,tol:.0005},{id:'size60-tol002',size:60,tol:.002},{id:'chim',mode:1},{id:'phang',mode:2},{id:'phang2',mode:3},{id:'no-closing-control',weld:0},{id:'invalid-size',size:0,refusal:'PARAMETER_DOMAIN'},{id:'point-budget',points:1500,refusal:'SUPPORT_POINT_BUDGET'}];
for(const c of cases){const w=Buffer.from(base);if(c.size!==undefined)set(w,8,c.size);if(c.mode!==undefined)set(w,25,c.mode);if(c.weld!==undefined)set(w,12,c.weld);if(c.tol!==undefined)w.writeDoubleLE(c.tol,200);if(c.points!==undefined)w.writeUInt32LE(c.points,48);
 const wp=path.join(out,c.id+'.aprq'),prefix=path.join(out,c.id);fs.writeFileSync(wp,w);const r=invoke('replay_candidate',[source,wp,prefix]);fs.writeFileSync(prefix+'.log',r.stdout);const s=readProductSemantics(fs.readFileSync(prefix+'.apms'));
 const row={id:c.id,sourceVerdict:s.sourceVerdict,mechanicsVerdict:s.mechanicsVerdict,blocked:s.exportBlocked,sourceDiagnostics:s.sourceDiagnostics,diagnostics:s.diagnostics};
 if(c.refusal){assert.ok(s.exportBlocked);assert.ok(s.sourceDiagnostics.some(d=>d.message===c.refusal),JSON.stringify(row));assert.ok(!fs.existsSync(prefix+'.arch'));row.expected='typed invalid/resource; no mesh';}
 else{assert.equal(s.sourceVerdict,0,JSON.stringify(row));assert.equal(s.mechanicsVerdict,0,JSON.stringify(row));assert.equal(s.exportBlocked,false);const bytes=fs.readFileSync(prefix+'.arch'),scene=readSnapshot(bytes),parts=scene.parts.map(p=>partMesh(scene,p));row.parts=parts.length;row.mesh=parts.map((p,i)=>({id:s.parts[i].id,...inspectMesh(p),bbox:bbox(p)}));row.parameters=s.parameters;row.sourceErrors=s.sourceErrors;row.sourceTransform=s.sourceTransform;row.sourceHash=sha(fs.readFileSync(source));assert.equal(s.sourceToleranceMm,c.tol??.001);assert.ok(s.sourceErrors.find(e=>e.stage===100).signedMaxMm<=s.sourceToleranceMm);assert.equal(s.proposals.length,0);
  // Raw provenance and identity tables remain byte-identical to the captured request.
  const originalCount=base.readUInt32LE(40),tail=base.subarray(base.length-originalCount);assert.deepEqual(s.provenance,JSON.parse(tail));assert.equal(s.inputRegions.length,7);assert.equal(s.inputRegions.reduce((n,p)=>n+p.ringCount,0),12);
  for(const p of s.parameters){let at=-1;for(let i=0;i<w.readUInt32LE(16);i++)if(w.readUInt32LE(256+i*40)===p.fieldId)at=256+i*40;if(at>=0){assert.equal(p.value,w.readDoubleLE(at+24));assert.equal(p.mode,w.readUInt32LE(at+4));assert.equal(p.origin,w.readUInt32LE(at+8));assert.equal(p.datum,w.readUInt32LE(at+12));assert.equal(p.referenceLayer,w.readUInt32LE(at+16));assert.equal(p.provenanceId,w.readBigUInt64LE(at+32).toString());}}
 }
 rows.push(row);fs.writeFileSync(path.join(out,'models.json'),JSON.stringify(rows,null,2));console.log(JSON.stringify({id:row.id,status:'pass',parts:row.parts??0}));
}
const before=path.join(out,'legacy');invoke('replay_before',[source,path.join(fixture,'bevietnampro-nfd.aprq'),before]);const b=readProductSemantics(fs.readFileSync(before+'.apms'));assert.ok(b.exportBlocked);assert.equal(b.sourceDiagnostics.at(-1).message,'SUPPORT_REGULARIZATION_BOUND');
const input=path.join(fixture,'derived-support.paths'),audit=path.join(out,'support.json');invoke('support_paths',[input,audit,'6400000']);const a=JSON.parse(fs.readFileSync(audit));const numeric=a.rings.map(r=>{const prior=auditChain(r.original,r.proposal),after=auditChain(r.original,r.result,2);assert.ok(after.maxGrid<=r.boundGrid);return {prior,after,refinements:r.refinements,reportedBoundGrid:r.boundGrid};});assert.ok(numeric.some(r=>r.prior.maxGrid>2));assert.ok(numeric.every(r=>r.after.maxGrid<=2));
for(const row of a.rings)for(let i=0;i<row.result.length;i++){const p=row.result[i],q=row.result[(i+1)%row.result.length];assert.ok(Math.max(Math.abs(p[0]-q[0]),Math.abs(p[1]-q[1]))>=2,'retained support edge guard');}
const denied=path.join(out,'work-exhausted.json');invoke('support_paths',[input,denied,'3'],1);assert.ok(!fs.existsSync(denied),'budget failure publishes nothing');
fs.writeFileSync(path.join(out,'numeric.json'),JSON.stringify({work:a.work,rings:numeric},null,2));fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify({target,phase,models:rows.length,positiveModels:rows.filter(r=>!r.blocked).length,legacyRefusal:true,exactNumeric:numeric,workBudgetRefusal:true,scope:'exact captured root source/request; unchanged root C++ bridge+mechanics, candidate source child; no Rust Worker/browser qualification'},null,2));
