import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';import http from 'node:http';
const root=process.env.PROJECT_ROOT,run=process.env.PROJECT_REVIEW_RUN,base=path.resolve(import.meta.dirname,'../..'),label=process.env.SOURCE_SVG_LABEL??'browser-attempt';
const hash=b=>createHash('sha256').update(b).digest('hex'),fixture=JSON.parse(fs.readFileSync(path.join(run,'inputs/source-fixture.json'))),pins=JSON.parse(fs.readFileSync(path.join(run,'inputs/runtime-api-production.json'))).module;
const publicRoot=path.join(run,'work/browser-'+label);fs.mkdirSync(publicRoot,{recursive:true});
const {rolldown}=await import(pathToFileURL(path.join(root,'.toolchain/app-runtime/node_modules/rolldown/dist/index.mjs')));
const build=await rolldown({input:{browser:path.join(base,'tests/source-svg-export/browser-entry.mjs'),engine:path.join(base,'src/core/engine-worker.mjs')},platform:'browser'});
try{await build.write({dir:publicRoot,format:'es',entryFileNames:'[name].mjs',chunkFileNames:'[name]-[hash].mjs'});}finally{await build.close();}
const files=new Map();for(const e of fs.readdirSync(publicRoot)){const b=fs.readFileSync(path.join(publicRoot,e));files.set('/'+e,{bytes:b,type:'text/javascript; charset=utf-8'});}
for(const [i,ext]of ['mjs','wasm'].entries()){const b=fs.readFileSync(path.join(run,'work/module/arch-kernel.'+ext));assert.equal(hash(b),pins[i].sha256);files.set('/module/arch-kernel.'+ext,{bytes:b,type:ext==='mjs'?'text/javascript':'application/wasm'});}
for(const a of fixture.actualAssets){const b=fs.readFileSync(path.join(run,'inputs/library',a.sha256));assert.equal(hash(b),a.sha256);files.set('/library/'+a.sha256,{bytes:b,type:'application/octet-stream'});}
files.set('/',{bytes:Buffer.from('<!doctype html><meta charset="utf-8"><title>Source SVG RPC test</title><script type="module" src="/browser.mjs"></script>'),type:'text/html; charset=utf-8'});
const server=http.createServer((req,res)=>{const f=files.get(req.url);res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy','require-corp');res.setHeader('Cross-Origin-Resource-Policy','same-origin');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control','no-store');res.setHeader('Content-Security-Policy',"default-src 'none'; script-src 'self' 'wasm-unsafe-eval'; worker-src 'self'; connect-src 'self'; font-src 'self'; img-src 'none'; object-src 'none'; base-uri 'none'");if(req.method!=='GET'||!f){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',f.type);res.end(f.bytes);});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,assetURLs=fixture.assetRecords.map(r=>({...r,url:origin+'/library/'+r.sha256}));
const pw=await import(pathToFileURL(path.join(root,'.toolchain/app-runtime/node_modules/playwright/index.mjs')));test.after(()=>new Promise(r=>{server.closeAllConnections();server.close(r);}));
for(const [name,version]of [['chromium','153.0.8010.12'],['firefox','155.0'],['webkit','26.6']].filter(([name])=>!process.env.SOURCE_SVG_ENGINE||process.env.SOURCE_SVG_ENGINE===name))test('actual source-only parent RPC '+name,{timeout:360000},async()=>{
 const profile=path.join(run,'cache/browser-'+label,name),downloads=path.join(run,'cache/browser-'+label,name+'-downloads');fs.mkdirSync(profile,{recursive:true});fs.mkdirSync(downloads,{recursive:true});
 const context=await pw[name].launchPersistentContext(profile,{headless:true,downloadsPath:downloads,...(name==='firefox'?{firefoxUserPrefs:{'network.proxy.type':0}}:{}),env:{...process.env,APPDATA:path.join(run,'cache/browser-'+label,'appdata'),LOCALAPPDATA:path.join(run,'cache/browser-'+label,'localappdata')}});
 let blocked=0;const errors=[];try{assert.equal(context.browser().version(),version);await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin!==origin||!files.has(u.pathname)){blocked++;return r.abort();}return r.continue();});const page=context.pages()[0]??await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForFunction(()=>typeof globalThis.runSourceSVG==='function');
  const phases=[];let timer;const tick=setInterval(()=>{void page.evaluate(()=>globalThis.sourceSVGPhase).then(phase=>{if(phases.at(-1)?.phase!==phase){const row={phase,elapsed:Date.now()-began};phases.push(row);console.log(name+' '+JSON.stringify(row));}}).catch(()=>{});},2000),began=Date.now();let result;try{result=await Promise.race([page.evaluate(args=>globalThis.runSourceSVG(args),{catalog:fixture.catalog,assetURLs,runtime:{engine:name,version}}),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('SOURCE_SVG_BROWSER_DEADLINE:'+JSON.stringify(phases))),270000);})]);}catch(error){fs.mkdirSync(path.join(run,'evidence/browser-'+label,name),{recursive:true});fs.writeFileSync(path.join(run,'evidence/browser-'+label,name,'failure.json'),JSON.stringify({error:String(error),phases,errors,blocked,module:pins},null,2));throw error;}finally{clearTimeout(timer);clearInterval(tick);}assert.equal(result.status,'passed');assert.equal(result.rows.length,5);assert.equal(result.modelBuilds,0);assert.equal(result.rootRuntimeInitializations,1);assert.equal(result.crossOriginIsolated,true);assert.deepEqual(errors,[]);assert.equal(blocked,0);
  const dir=path.join(run,'evidence/browser-'+label,name);fs.mkdirSync(dir,{recursive:true});for(const f of result.files)fs.writeFileSync(path.join(dir,f.name),new Uint8Array(f.bytes));delete result.files;fs.writeFileSync(path.join(dir,'result.json'),JSON.stringify({...result,browser:name,version,blocked,module:pins},null,2));
 }finally{await context.close();}
});
