import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const room=process.env.PROJECT_REVIEW_RUN,root=process.env.PROJECT_ROOT;assert.equal(path.basename(room??''),'20260908-source-assembly-wave1');
const candidate=path.join(room,'work/source-assembly'),reports=path.join(room,'reports');
assert.ok(!fs.existsSync(path.join(reports,'FROZEN.json')),'Already frozen; use a fresh run');
const read=p=>JSON.parse(fs.readFileSync(path.join(room,p))),sha=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const native=read('evidence/source-native-results.json'),wasm=read('evidence/source-wasm-results.json'),parity=read('evidence/native-wasm-parity.json'),domain=read('evidence/domain-bindings.json');
for(const r of [native,wasm,domain,read('evidence/bridge-native-results.json'),read('evidence/bridge-wasm-results.json')])assert.equal(r.passed,r.total);
const definitions=[
 ['noi','Raised colors, overrides and nominal Z','MOD-03 / GEO-02',['style-0','override','nominal-'],'264*2.4 + 200*.8 = 793.6 mm3; explicit 1.7/5.5/1.85 mm retained'],
 ['chim','Recessed colored floor with intentional open well','MOD-03 / GEO-02',['style-1','recess-layers'],'264*2.4 - 200*.8 = 473.6 mm3; probes above floor are empty'],
 ['phang','Color mosaic inside body height','MOD-03',['style-2'],'633.6 mm3 total, top at2.4 mm'],
 ['phang2','Added flat color mosaic','MOD-03',['style-3','flat-layers'],'897.6 mm3 total, top at3.4 mm'],
 ['body','Silhouette, rounded/capsule, circle and square','GEO-01 / MOD-03',['body-','circle-'],'Analytic rectangle/capsule/circle area, three sizes and tolerances'],
 ['holes','Original art holes and explicit body-hole policy','GEO-01 / AT-020.3',['hole-'],'4 mm2 counter through all four modes; material/void probes'],
 ['disconnected','Accents, weld and support-width proposals','SRC-04 / GEO-01',['accent-','body-weld'],'No accent deletion; explicit component erosion diagnostic/proposal'],
 ['rim','Distinct support material and interval','MOD-03',['style-','rim-layers'],'264*.6 mm3 added only in defined additive modes; exact layer spans'],
 ['bands-core','Material height bands and body-colored core','MOD-03',['bands','core','cap-layers','inactive-override'],'873.6 mm3; separate core/cap probes; no clamping of overrides'],
 ['text','Prepared glyphs, text base and stepped support','SRC-04 / MOD-02',['text-'],'Analytic rounded base area; source subtraction; positive face contact'],
 ['bed-text','Bed Z independent of body datum and preview','SRC-04 / ABI-01',['bed-'],'Text/base min Z0, max1.4, group2 identity preview; tray collision rejected'],
 ['schedule','First/regular and feature-relative spans','GEO-02 / AT-021.2/.4',['first-layers','relative-layers','nominal-','text-layers'],'h0=.27, h=.16/.20/.25; no vertex snap or input mutation'],
 ['materials','User role/region values and provenance','MOD-02',['color-overrides','stable-'],'User region wins; role overrides and uint64 source identity retained'],
 ['contacts','Actual 3D contacts and exact shared source boundaries','GEO-01 / AT-020.2',['contact-','large-slope','indexed'],'8 mm2 vertical face and two100 mm2 horizontal contacts; disjoint Z not contact'],
 ['products','Prepared source across five product executors','MOD-01',['product-'],'All four modes on all five products with normal supporting source footprints'],
 ['bevel-groove','Source/slab preservation through existing feature executor','MOD-03 / GEO-03',['bevel-style','groove-section'],'Actual top profiles and groove radial oracle; final blind-bore wall guard is separate pending remediation'],
 ['invalid','Typed invalid input, proposals, budgets and cancellation','MOD-03 / ABI-01',['invalid-','budget-','cancel-','wrong-footprint','clicky-size-proposal'],'No partial source/mesh publication; input parameters stay unchanged'],
 ['seeded','Reproducible numerical corner cases','QA-01 / QA-04',['seed-'],'24 seed0x5a17c0de analytic size/height/pad combinations; per-case reproducers'],
];
const rows=definitions.map(([id,feature,requirements,prefixes,oracle])=>{const cases=native.cases.filter(c=>prefixes.some(p=>c.id.startsWith(p))).map(c=>c.id);assert.ok(cases.length);return{id,feature,requirements,oracle,status:'pass (component scope)',nativeCases:cases,wasmCases:cases};});
const matrix={schemaVersion:1,sourceAbi:1,sourceSemantics:1,mechanicsAbi:2,configuredReview:false,physicalFit:'unqualified',rows,limits:['minFeature component erosion does not certify every local neck','canonical opaque XY required; decoder/shaping/raster uncertainty stays upstream','root runtime/browser/exporter and physical qualification are separate','parent-reported mechanics findings001..007 pending bounded remediation after this source freeze']};
fs.writeFileSync(path.join(candidate,'docs/acceptance.json'),JSON.stringify(matrix,null,2)+'\n');
fs.writeFileSync(path.join(candidate,'docs/ACCEPTANCE.md'),'# Source component acceptance — semantics1\n\nImplementation evidence, not configured independent review or full application/physical acceptance.\n\n| Feature | Requirement | Actual oracle | Result |\n|---|---|---|---|\n'+rows.map(r=>`| ${r.id}: ${r.feature} | ${r.requirements} | ${r.oracle} | pass in component scope |`).join('\n')+'\n\nNative140/140 and WASM140/140; mechanics bridge regressions13/13 each; domain bindings13/13. Complete per-case links and scope limits are in acceptance.json and the checked evidence manifests. Field checks are not counted as complete feature acceptance.\n');
function walk(base){const result=[];function visit(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){assert.ok(!e.isSymbolicLink());const p=path.join(dir,e.name);if(e.isDirectory())visit(p);else result.push({path:path.relative(base,p).replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:sha(p)});}}visit(base);return result.sort((a,b)=>a.path<b.path?-1:1);}
const dependency=[];for(const folder of ['src','include','cmake'])for(const f of walk(path.join(root,'.toolchain/manifold',folder)))dependency.push({...f,path:'.toolchain/manifold/'+folder+'/'+f.path});for(const f of ['CMakeLists.txt','LICENSE','AUTHORS']){const p=path.join(root,'.toolchain/manifold',f);if(fs.existsSync(p))dependency.push({path:'.toolchain/manifold/'+f,bytes:fs.statSync(p).size,sha256:sha(p)});}
fs.writeFileSync(path.join(reports,'dependency-source-manifest.json'),JSON.stringify({purpose:'Actual read-only pinned Manifold source including supplied context extension; compiled input bytes, not just HEAD label',files:dependency},null,2)+'\n');
for(const f of read('inputs/mechanics-checked-manifest.json').files)assert.equal(sha(path.join(room,'inputs/mechanics-v2',f.path)),f.sha256,'frozen mechanics input '+f.path);
const checked={schemaVersion:1,component:'arch-source-assembly/0.1.0',scope:'implementation-only',sourceAbi:1,sourceSemantics:1,mechanicsAbi:2,configuredReview:false,files:walk(candidate)};
fs.writeFileSync(path.join(reports,'checked-manifest.json'),JSON.stringify(checked,null,2)+'\n');
const checkedSha=sha(path.join(reports,'checked-manifest.json')),release='source-assembly-'+checkedSha.slice(0,16);
const evidencePaths=[];for(const d of ['tests-native','tests-wasm','bridge-native','bridge-wasm'])for(const f of walk(path.join(room,'evidence',d)))evidencePaths.push({...f,path:'evidence/'+d+'/'+f.path});
for(const f of ['source-native-results.json','source-wasm-results.json','bridge-native-results.json','bridge-wasm-results.json','domain-bindings.json','native-wasm-parity.json','mechanics-bridge.json','source-native-build.log','source-wasm-build.log','source-native-configure.log','source-wasm-configure.log']){const p=path.join(room,'evidence',f);evidencePaths.push({path:'evidence/'+f,bytes:fs.statSync(p).size,sha256:sha(p)});}
fs.writeFileSync(path.join(reports,'evidence-manifest.json'),JSON.stringify({schemaVersion:1,release,files:evidencePaths},null,2)+'\n');
const handoff={schemaVersion:1,release,candidate:path.relative(root,candidate).replaceAll('\\','/'),checkedManifestSha256:checkedSha,sourceComponentReady:true,overallMechanicsReleaseQualified:false,native:{passed:native.passed,total:native.total},wasm:{passed:wasm.passed,total:wasm.total},bridgeRegression:13,domain:domain.total,parity:{cases:parity.cases,maxBBoxDelta:parity.maxBBoxDelta,maxVolumeDelta:parity.maxVolumeDelta,maxSectionDelta:parity.maxSectionDelta,mainOracleParts:parity.mainOracle.meshPartsChecked},physicalFit:'unqualified',configuredReview:false,deltaOwnership:{newTarget:'src/kernel/source-assembly (parent-selected integration destination)',patch:'compat/mechanics-source-integration.patch',mechanicsFiles:['src/kernel/mechanics/src/mechanics.cpp','src/kernel/mechanics/src/mechanics.h','src/kernel/mechanics/src/domain-adapter.mjs'],rootWritesPerformed:false},pendingMechanicsRemediation:['001 final blind-bore wall/roof guards after bevel/groove','002 impOn activation mask across all products','003 optional mm datum/reference: bridge already has13 domain checks; compare actual review reproducers next','004 nearest-layer tie span parity','005 BODY_BOTTOM/skirt datum ambiguity','006 topBevelSeg integer validation','007 zero collar inactive radius'],wave2Base:'mechanics-wave2-f09a6fc371be0af0',limits:matrix.limits};
fs.writeFileSync(path.join(reports,'handoff.json'),JSON.stringify(handoff,null,2)+'\n');
fs.writeFileSync(path.join(reports,'HANDOFF.md'),`# ${release}\n\nSource component checked and frozen for parent integration. Candidate: work/source-assembly. Checked manifest SHA256: ${checkedSha}.\n\nNative140/140, WASM140/140, bridge13/13 each, domain13/13; parity140 cases, bbox delta0, section delta0, max volume delta ${parity.maxVolumeDelta} mm3. Current main mesh oracle reran ${parity.mainOracle.meshPartsChecked} parts.\n\nCopy only files in checked-manifest.json. Apply compat/mechanics-source-integration.patch after parent checks it; it targets three mechanics files listed in handoff.json. Root and frozen wave2 were not edited. API/header and acceptance matrix are in candidate docs. Static native/WASM CMake targets were built against read-only pinned libraries.\n\nThis freezes source composition, not a claim that the complete mechanics release is qualified. Parent-reported mechanics findings001..007 are queued for bounded remediation in a fresh private run after this freeze. The source bridge preserves optional mm datum/reference (13 domain cases); that finding still needs comparison against the independent review reproducer. No export default is changed to hide downstream issues.\n\nImplementation-only, inherited Astra/max per user, fast unavailable/unverified; no configured independent-review or physical-fit claim. Immutable record is FROZEN.json.\n`);
const published=['reports/checked-manifest.json','reports/evidence-manifest.json','reports/dependency-source-manifest.json','reports/HANDOFF.md','reports/handoff.json'].map(p=>({path:p,sha256:sha(path.join(room,p))}));
const freeze={schemaVersion:1,release,at:new Date().toISOString(),sourceFiles:checked.files.length,evidenceFiles:evidencePaths.length,files:published};fs.writeFileSync(path.join(reports,'FROZEN.json'),JSON.stringify(freeze,null,2)+'\n');
for(const f of checked.files)fs.chmodSync(path.join(candidate,f.path),0o444);for(const f of evidencePaths)fs.chmodSync(path.join(room,f.path),0o444);for(const f of [...published,{path:'reports/FROZEN.json'}])fs.chmodSync(path.join(room,f.path),0o444);
console.log(JSON.stringify({release,checkedManifestSha256:checkedSha,files:checked.files.length,evidenceFiles:evidencePaths.length}));
