import test from'node:test';import assert from'node:assert/strict';import{readFile,writeFile,mkdir}from'node:fs/promises';import path from'node:path';import{pathToFileURL}from'node:url';import{createHash}from'node:crypto';
import{createProductOperations}from'../../src/core/product-operations.mjs';import{encodeFinalFloatPrepare,encodeFinalFloatConfirmation,prepareFinalFloat,confirmFinalFloat,encodeFinalSceneGeometry,finalSceneGeometry}from'../../src/kernel/final-scene-export/float-runtime.mjs';import{encodeFinalExportOptions,exportFinalFileBytes}from'../../src/kernel/final-scene-export/runtime-helper.mjs';import{readSnapshot,readSTL,inspectMesh}from'../oracles/mesh-oracle.mjs';import{source,makeRequest}from'../product-runtime/fixtures.mjs';
const run=process.env.PROJECT_REVIEW_RUN,modulePath=process.env.ARCH_WASM_MODULE;if(!run||!modulePath)throw Error('Own run/module required');const out=path.join(run,'evidence/float-node');await mkdir(out,{recursive:true});const hash=b=>createHash('sha256').update(b).digest('hex'),M=await(await import(pathToFileURL(modulePath))).default({print:()=>{},printErr:()=>{}});let generation=0;const next=()=>{assert.equal(M._arch_control_reset(++generation),1);return generation;};
const copy=id=>M.HEAPU8.slice(M._arch_snapshot_ptr(id),M._arch_snapshot_ptr(id)+M._arch_snapshot_len(id));const input=b=>{const id=M._arch_input_create(b.length);assert.ok(id);M.HEAPU8.set(b,M._arch_input_ptr(id));return id;};const error=()=>new TextDecoder().decode(M.HEAPU8.slice(M._arch_error_ptr(),M._arch_error_ptr()+M._arch_error_len()));const output=id=>M.HEAPU8.slice(M._arch_final_output_ptr(id),M._arch_final_output_ptr(id)+M._arch_final_output_len(id));
function config(id,revision='1'){const mesh=readSnapshot(copy(id));return {format:1,generation:mesh.generation,gates:0,verdict:1,inspection:0,revision,expectedRevision:revision,filename:'float',mapping:mesh.parts.map((p,part)=>({part,slot:1,rgba:p.color,source:p.source,materialSource:part+1,reserved:0}))};}
function geom(c){return {revision:c.revision,expectedRevision:c.expectedRevision,mapping:c.mapping.map(({reserved,...x})=>x)};}
const policy={version:1,maximumDisplacementMm:.00001,workLimit:50_000_000};
test('same-module identity and versioned wire defensive checks',()=>{
 assert.equal(M._arch_abi_version(),2);assert.equal(M._arch_final_float_version(),1);assert.equal(M._arch_final_scene_geometry_version(),1);assert.equal(M._arch3mf_abi_version(),1);assert.equal(M._arch3mf_kernel_abi_version(),2);assert.equal(typeof M._hb_buffer_create,'function');
 assert.throws(()=>encodeFinalSceneGeometry({revision:'1',expectedRevision:'1',mapping:[]},1));assert.throws(()=>encodeFinalFloatConfirmation({version:'wrong'}));for(const x of [NaN,Infinity,-1,0,.005])assert.throws(()=>encodeFinalFloatPrepare({}, {...policy,maximumDisplacementMm:x}));
 const stale=input(new Uint8Array(64));assert.equal(M._arch_final_float_prepare(0,stale,next()),0);assert.equal(M._arch_input_release(stale),0);const countOverflow=new Uint8Array(64),od=new DataView(countOverflow.buffer);[0x50434641,1,64,64,0xffffffff].forEach((v,i)=>od.setUint32(i*4,v,true));const overflowInput=input(countOverflow);assert.equal(M._arch_final_float_prepare(1,overflowInput,next()),0);assert.equal(error(),'FLOAT_PREPARE_WIRE_LENGTH_FLAGS');assert.equal(M._arch_input_release(overflowInput),0);assert.equal(M._arch_final_float_prepare(1,0xfffffff0,next()),0);assert.equal(error(),'INPUT_HANDLE_INVALID');
});
test('material union keeps distinct identities and positive overlap for checker',async()=>{
 const id=M._arch_final_test_fixture(0,next());assert.ok(id);try{const before=hash(copy(id)),c=config(id),r=geom(c);
 r.mapping=r.mapping.map(m=>({...m,rgba:0xff0000ff,slot:1,materialSource:42}));const united=finalSceneGeometry(M,id,c.generation,r,next()),one=readSnapshot(united.bytes);assert.equal(one.parts.length,1);assert.ok(Math.abs(inspectMesh(one).volume-1500)<1e-8);
 r.mapping[1].materialSource=43;const split=finalSceneGeometry(M,id,c.generation,r,next()),two=readSnapshot(split.bytes);assert.equal(two.parts.length,2);assert.deepEqual(split.metadata.groups.map(g=>g.materialSource),[42,43]);assert.equal(split.metadata.meshVerdict,'unverified');assert.ok(split.metadata.nativeWarningFlags>0);
 const volumes=two.parts.map(p=>inspectMesh({vertices:two.vertices,faces:two.faces.slice(p.faceStart,p.faceStart+p.faceCount)}).volume);const exactVolume6=p=>two.faces.slice(p.faceStart,p.faceStart+p.faceCount).reduce((sum,t)=>{const [a,b,c]=t.map(i=>two.vertices[i].map(x=>{assert.ok(Number.isInteger(x));return BigInt(x);}));return sum+a[0]*(b[1]*c[2]-b[2]*c[1])-a[1]*(b[0]*c[2]-b[2]*c[0])+a[2]*(b[0]*c[1]-b[1]*c[0]);},0n);const six=two.parts.map(exactVolume6);assert.deepEqual(six,[6000n,6000n]);assert.equal(six.reduce((a,b)=>a+b)-9000n,3000n,'exact analytic inter-material overlap 500mm3 is retained');assert.equal(hash(copy(id)),before);
 const bytes=encodeFinalSceneGeometry(r,c.generation);for(const at of [4,8,12,40,60]){const bad=bytes.slice();bad[at]^=1;const h=input(bad);assert.equal(M._arch_final_scene_geometry(id,h,next()),0);assert.equal(M._arch_input_release(h),0);}
 const g=next();Atomics.store(new Int32Array(M.HEAPU8.buffer,M._arch_control_ptr(),4),3,g);assert.equal(M._arch_final_scene_geometry(id,input(bytes),g),0);assert.equal(error(),'CANCELLED');assert.equal(hash(copy(id)),before);
 await writeFile(path.join(out,'material-overlap.arch'),split.bytes);await writeFile(path.join(out,'material-overlap.json'),JSON.stringify({metadata:split.metadata,volumes,analyticUnion:1500,analyticOverlap:500},null,2));}finally{M._arch_snapshot_release(id);}
});
test('registered allocations, fresh memory views, retained outputs, source authority and default clicky',async()=>{
 const ops=createProductOperations(M);const build=(assembly=false)=>{const r=makeRequest('clicky','noi',{sourceHash:hash(source),headHash:hash('node-clicky'),changes:assembly?[{id:'assemble',value:true}]:[]}),g=next();const h=ops.prepare({kind:'product',source:{kind:'svg',source},packed:r.packed},g);return {id:ops.buildRequest(h,g),revision:String(r.project.revision)};};
 const s=build(),id=s.id,c=config(id,s.revision),before=hash(copy(id));assert.throws(()=>exportFinalFileBytes(M,id,encodeFinalExportOptions(c),next()),/STL_FLOAT_COLLISION/);
 const p=prepareFinalFloat(M,id,c,policy,next()),q=p.metadata.confirmation,originalHash=hash(M.HEAPU8.slice(p.buffers[2].byteOffset,p.buffers[2].byteOffset+p.buffers[2].byteLength));
 const oldMemory=M.HEAPU8.buffer,allocs=[];for(let i=0;i<4;i++){const h=M._arch_input_create(16*1024*1024);assert.ok(h);allocs.push(h);}assert.notEqual(M.HEAPU8.buffer,oldMemory,'real registered inputs force memory growth');for(const h of allocs)M._arch_input_release(h);assert.equal(hash(M.HEAPU8.slice(M._arch_final_float_buffer_ptr(p.id,3),M._arch_final_float_buffer_ptr(p.id,3)+M._arch_final_float_buffer_len(p.id,3))),originalHash);
 assert.throws(()=>confirmFinalFloat(M,p.id,{...q,sourceHash:'0'.repeat(64)},next()),/STALE_CONTEXT/);
 const confirmation=encodeFinalFloatConfirmation(q),held=[];let first;
 for(let i=0;i<4;i++){const file=M._arch_final_float_confirm(p.id,input(confirmation),next());assert.ok(file,error());held.push(file);first??=output(file);assert.equal(hash(output(file)),hash(first));}
 assert.equal(M._arch_final_float_confirm(p.id,input(confirmation),next()),0);assert.equal(error(),'FINAL_OUTPUT_RESOURCE_LIMIT');for(const file of held){assert.equal(hash(output(file)),hash(first));M._arch_final_output_release(file);}
 assert.equal(hash(copy(id)),before);assert.equal(M._arch_snapshot_release(id),1);assert.ok(M._arch_snapshot_ptr(id));const file=confirmFinalFloat(M,p.id,q,next());assert.equal(hash(file.bytes),hash(first));assert.equal(M._arch_final_float_release(p.id),1);assert.equal(M._arch_snapshot_ptr(id),0);
 const a=build(true),ac=config(a.id,a.revision);assert.throws(()=>prepareFinalFloat(M,a.id,ac,policy,next()),/ASSEMBLY_VIEW/);assert.throws(()=>finalSceneGeometry(M,a.id,ac.generation,geom(ac),next()),/ASSEMBLY_VIEW/);assert.throws(()=>finalSceneGeometry(M,a.id,ac.generation,{...geom(ac),revision:'99',expectedRevision:'99'},next()),/ASSEMBLY_VIEW|STALE_REVISION/);M._arch_snapshot_release(a.id);
 assert.equal(M._arch_final_float_confirm(p.id,input(confirmation),next()),0);assert.equal(error(),'FLOAT_PROPOSAL_HANDLE_INVALID');assert.ok(inspectMesh(readSTL(Buffer.from(file.bytes))).volume>0);await writeFile(path.join(out,'default-clicky.stl'),file.bytes);await writeFile(path.join(out,'default-clicky.json'),JSON.stringify({metadata:file.metadata,growth:true,sha256:hash(file.bytes)},null,2));
 for(let k=0;k<5;k++)assert.equal(M._arch_final_test_stats(k),0,'root allocation statistic '+k);
});
