import test from 'node:test';import assert from 'node:assert/strict';import{readFile,writeFile,mkdir,readdir}from'node:fs/promises';import path from'node:path';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';import{createServer}from'node:http';
import{build}from'vite';import{chromium,firefox,webkit}from'playwright';import{source,makeRequest}from'../product-runtime/fixtures.mjs';import{readSnapshot,readSTL,inspectMesh}from'../oracles/mesh-oracle.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url)),run=process.env.PROJECT_REVIEW_RUN,modulePath=process.env.ARCH_WASM_MODULE;if(!run||!modulePath)throw Error('PROJECT_REVIEW_RUN and ARCH_WASM_MODULE required');
const out=path.join(run,'evidence/float-workers'),bundle=path.join(run,'work/float-worker-bundle');await mkdir(out,{recursive:true});const hash=b=>createHash('sha256').update(b).digest('hex');
const configs={};for(const[product,changes,name]of [['clicky',[],'clicky'],['clicky',[{id:'assemble',value:true}],'assembly']]){const r=makeRequest(product,'noi',{sourceHash:hash(source),headHash:hash('float-'+name),changes});configs[name]={packed:Array.from(r.packed),revision:String(r.project.revision)};}
await build({configFile:false,root,cacheDir:path.join(run,'cache/vite-float-workers'),logLevel:'warn',build:{target:'es2022',modulePreload:false,outDir:bundle,emptyOutDir:false,minify:false,rollupOptions:{input:path.join(root,'src/core/engine-worker.mjs'),output:{entryFileNames:'engine-worker.mjs',chunkFileNames:'chunks/[name]-[hash].mjs'}}}});
const routes=new Map();async function add(dir){for(const e of await readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())await add(p);else routes.set('/src/core/'+path.relative(bundle,p).replaceAll('\\','/'),await readFile(p));}}await add(bundle);for(const name of ['engine-client.mjs','source-frame.mjs','runtime-integrity.mjs'])routes.set('/src/core/'+name,await readFile(path.join(root,'src/core',name)));for(const ext of ['mjs','wasm'])routes.set('/runtime/arch-kernel.'+ext,await readFile(modulePath.replace(/\.mjs$/,'.'+ext)));
const server=createServer((req,res)=>{for(const[k,v]of Object.entries({'Cross-Origin-Opener-Policy':'same-origin','Cross-Origin-Embedder-Policy':'require-corp','Cross-Origin-Resource-Policy':'same-origin','Cache-Control':'no-store'}))res.setHeader(k,v);if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>Actual root float Worker tests</title>');return;}const b=routes.get(req.url);if(!b){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',req.url.endsWith('.wasm')?'application/wasm':'text/javascript');res.end(b);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;test.after(()=>new Promise(r=>{server.closeAllConnections();server.close(r);}));
for(const[engine,browserType]of Object.entries({chromium,firefox,webkit}))test('actual unified root float and material readback '+engine,{timeout:120000},async()=>{
 const context=await browserType.launchPersistentContext(path.join(run,'p/float-'+engine),{headless:true,downloadsPath:path.join(run,'work/float-downloads',engine),...(engine==='firefox'?{firefoxUserPrefs:{'network.proxy.type':0}}:{})});const page=context.pages()[0],errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{await context.route('**/*',r=>r.request().url().startsWith(origin+'/')?r.continue():r.abort());await page.goto(origin);const result=await page.evaluate(async({source,configs})=>{
  const{EngineClient}=await import('/src/core/engine-client.mjs');const client=new EngineClient({moduleURL:'/runtime/arch-kernel.mjs',cancelGraceMs:5000});let generation=0,root,proposal;const checks=[];
  const ck=(c,s)=>{if(!c)throw Error('CHECK '+s);checks.push(s);};const fail=async f=>{try{await f();return 'NO_ERROR';}catch(e){return e.code??e.message;}};const hash=async b=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(b))),v=>v.toString(16).padStart(2,'0')).join('');
  const make=async name=>client.build({kind:'product',source:{kind:'svg',source},packed:new Uint8Array(configs[name].packed)},{generation:++generation});
  const options=(lease,revision)=>{const b=lease.bytes(),d=new DataView(b.buffer,b.byteOffset,b.byteLength),n=d.getUint32(28,true),p=d.getUint32(56,true);return {format:1,generation:lease.generation,gates:0,verdict:1,inspection:0,revision,expectedRevision:revision,filename:'float',mapping:Array.from({length:n},(_,part)=>({part,slot:1,rgba:d.getUint32(p+part*40+16,true),source:d.getUint32(p+part*40+20,true),materialSource:part+1,reserved:0}))};};
  const geometryOptions=c=>({revision:c.revision,expectedRevision:c.expectedRevision,mapping:c.mapping.map(({reserved,...m})=>m)});
  const conditioning={version:1,maximumDisplacementMm:.00001,workLimit:50_000_000};
  try{
   root=await make('clicky');const before=await hash(root.bytes()),worker=client.worker,epoch=client.epoch,c=options(root,configs.clicky.revision);
   ck(client.serviceCapabilities.finalFloat&&client.serviceCapabilities.finalSceneGeometry,'capabilities verified from actual exports');const printing=client.serviceCapabilities.printingVersions;ck(printing?.rootABI===2&&printing.arch3mfABI===1&&printing.kernel3mfABI===2&&printing.epoch===epoch&&Object.isFrozen(printing),'actual same Module printing ABI 2/1/2 bound to client epoch');
   ck((await fail(()=>client.finalExport(root,c,{generation:++generation})))==='INVALID_SERIALIZATION','legacy Worker preserves serialization rejection code (native asserts exact collision detail)');
   const geometry=await client.finalSceneGeometry(root,geometryOptions(c),{generation:++generation});ck(geometry.metadata.meshVerdict==='unverified'&&geometry.metadata.geometry==='material-union','binary64 readback does not claim pass');ck(geometry.metadata.sourceSnapshotSha256===before&&geometry.metadata.sourceSnapshotId===root.id&&geometry.metadata.sourceSnapshotGeneration===root.generation,'readback exact source binding');
   ck(await fail(()=>client.finalSceneGeometry({...root},geometryOptions(c),{generation:++generation}))==='SNAPSHOT_LEASE_OWNERSHIP','geometry forged reader blocked');
   ck(await fail(()=>client.finalSceneGeometry(root,{...geometryOptions(c),revision:'99',expectedRevision:'99'},{generation:++generation}))==='STALE_REVISION','root geometry immutable product revision guard');
   const stale=await fail(()=>client.prepareFinalFloat(root,{...c,revision:'99',expectedRevision:'99'},conditioning,{generation:++generation}));ck(stale==='STALE_REVISION','prepare immutable product revision guard');
   const input=structuredClone(c),policy=structuredClone(conditioning),pending=client.prepareFinalFloat(root,input,policy,{generation:++generation});input.mapping[0].rgba=0;policy.maximumDisplacementMm=0;proposal=await pending;
   ck(!('bytes'in proposal)&&proposal.version==='arch-final-float-proposal/1','prepare publishes no file bytes');
   ck(proposal.metadata.conditioning.collapsedEdges===224&&proposal.metadata.conditioning.candidateTriangles===4840,'actual default clicky pair collision proposal');
   ck(proposal.metadata.conditioning.hausdorffUpperBoundMm<=.00001,'measured bounded proposal');
   const candidate=proposal.view(3),triangles=proposal.view(4);candidate[0]+=5;ck(proposal.view(3)[0]!==candidate[0],'public views are defensive typed copies');
   const expectedHash=await hash(proposal.view(3));ck(await fail(()=>client.confirmFinalFloat({...proposal},proposal.confirmation,{generation:++generation}))==='FLOAT_PROPOSAL_OWNERSHIP','forged proposal reader blocked');
   const wrong={...proposal.confirmation,proposalHash:'0'.repeat(64)};ck(await fail(()=>client.confirmFinalFloat(proposal,wrong,{generation:++generation}))==='FLOAT_CONDITIONING_APPROVAL_HASH','wrong hash rejected');
   for(const [field,value]of [['sourceRevision','99'],['sourceGeneration',99],['sourceHash','0'.repeat(64)],['optionsHash','0'.repeat(64)]])ck(await fail(()=>client.confirmFinalFloat(proposal,{...proposal.confirmation,[field]:value},{generation:++generation}))!=='NO_ERROR','changed '+field+' rejected');
   let cancelling=false;client.onStatus=s=>{if(s.phase==='running'&&!cancelling){cancelling=true;void client.cancel();}};ck(await fail(()=>client.confirmFinalFloat(proposal,proposal.confirmation,{generation:++generation}))==='CANCELLED','running confirm cancel');client.onStatus=()=>{};
   const file=await client.confirmFinalFloat(proposal,proposal.confirmation,{generation:++generation}),repeat=await client.confirmFinalFloat(proposal,proposal.confirmation,{generation:++generation});ck(await hash(file.bytes)===await hash(repeat.bytes),'confirmed bytes idempotent');
   const old=proposal;const second=await client.prepareFinalFloat(root,c,conditioning,{generation:++generation});const full=await fail(()=>client.prepareFinalFloat(root,c,conditioning,{generation:++generation}));ck(full==='FLOAT_PROPOSAL_RESOURCE_LIMIT','two bounded proposal slots');
   old.release();ck(await fail(()=>client.confirmFinalFloat(old,old.confirmation,{generation:++generation}))==='FLOAT_PROPOSAL_RELEASED','released token unusable');proposal=second;
   const replaced=await client.prepareFinalFloat(root,c,conditioning,{generation:++generation});ck(replaced.id!==old.id,'root IDs not reused after release');replaced.release();
   ck(await hash(proposal.view(3))===expectedHash,'earlier proposal unchanged across later allocations');ck(before===await hash(root.bytes()),'original source unchanged');root.release();root=null;
   const held=await client.confirmFinalFloat(proposal,proposal.confirmation,{generation:++generation});ck(await hash(held.bytes)===await hash(file.bytes),'proposal retains internal source reader');
   let other=await make('assembly');const ac=options(other,configs.assembly.revision);ck(await fail(()=>client.prepareFinalFloat(other,ac,conditioning,{generation:++generation}))==='ASSEMBLY_VIEW','assembly preparation guard');ck(await fail(()=>client.finalSceneGeometry(other,geometryOptions(ac),{generation:++generation}))==='ASSEMBLY_VIEW','assembly readback guard');other.release();
   ck(worker===client.worker&&epoch===client.epoch,'same Worker and Module for prepare/readback/confirm');
   // A replacement runtime can allocate the same native numeric ID; its epoch
   // cannot restore authority to the old exact lease (account/project ABA).
   const oldEpoch=proposal.epoch;client.terminate('TEST_PRIVATE_RETIRE');ck(client.serviceCapabilities.printingVersions===null,'printing ABI proof retired with runtime');const sequence=client.requestSequence;proposal.release();ck(await fail(()=>client.confirmFinalFloat(proposal,proposal.confirmation,{generation:++generation}))==='SNAPSHOT_RETIRED','retired epoch rejected without restart');ck(client.worker===null&&sequence===client.requestSequence,'retirement cleanup never restarts Worker');
   generation=0;root=await make('clicky');const rc=options(root,configs.clicky.revision),replacement=await client.prepareFinalFloat(root,rc,conditioning,{generation:++generation});ck(client.epoch!==oldEpoch,'replacement epoch changes');ck(client.serviceCapabilities.printingVersions?.epoch===client.epoch&&client.serviceCapabilities.printingVersions!==printing,'replacement obtains new printing getter proof');ck(await fail(()=>client.confirmFinalFloat(proposal,proposal.confirmation,{generation:++generation}))==='SNAPSHOT_RETIRED','ABA never reauthorizes old proposal');replacement.release();root.release();root=null;
   return {checks,sourceHash:before,metadata:old.metadata,file:Array.from(file.bytes),fileMetadata:file.metadata,geometry:Array.from(geometry.bytes),geometryMetadata:geometry.metadata};
  }finally{proposal?.release();root?.release();client.dispose();}
 },{source,configs});
 const stl=Buffer.from(result.file),materialBytes=Buffer.from(result.geometry);const metrics=inspectMesh(readSTL(stl)),m=readSnapshot(materialBytes);assert.equal(metrics.vertexCount,2424);assert.equal(metrics.faceCount,4840);assert.equal(metrics.euler,4);assert.ok(Math.abs(metrics.volume-14456.486695101785)<1e-8);assert.equal(m.parts.length,result.geometryMetadata.groups.length);assert.ok(m.parts.length>1);assert.equal(m.vertices.some(p=>p.some(x=>Math.fround(x)!==x)),true);
 const native=JSON.parse(await readFile(path.join(run,'evidence/native-root/result.json')));assert.equal(hash(stl),native.stlSha256);assert.equal(hash(materialBytes),hash(await readFile(path.join(run,'evidence/native-root/material-union.arch'))),'native/WASM binary64 material readback parity');assert.equal(result.sourceHash,native.sourceSha256);assert.equal(result.metadata.confirmation.proposalHash,native.proposalHash);assert.deepEqual(errors,[]);
 await writeFile(path.join(out,engine+'.stl'),stl);await writeFile(path.join(out,engine+'.arch'),materialBytes);delete result.file;delete result.geometry;await writeFile(path.join(out,engine+'.json'),JSON.stringify({status:'pass',engine,checks:result.checks.length,...result,metrics,errors,nativeParity:true},null,2));
 }catch(e){await writeFile(path.join(out,engine+'-failure.json'),JSON.stringify({error:e.stack,errors},null,2));throw e;}finally{await context.close();}
});
