if(TARGET expat)
 message(FATAL_ERROR "An existing expat target is not an attested archmi dependency; supply a separate verified integration")
endif()
if(NOT TARGET expat)
 if(NOT EXISTS "${ARCHMI_EXPAT_SOURCE}/CMakeLists.txt")
  message(FATAL_ERROR "Supply pinned Expat 2.8.4 source; no configure downloads")
 endif()
 foreach(opt TOOLS EXAMPLES TESTS DOCS FUZZERS PKGCONFIG)
  set(EXPAT_BUILD_${opt} OFF CACHE BOOL "" FORCE)
 endforeach()
 set(EXPAT_SHARED_LIBS OFF CACHE BOOL "" FORCE)
 set(EXPAT_DTD OFF CACHE BOOL "" FORCE)
 set(EXPAT_GE OFF CACHE BOOL "" FORCE)
 set(EXPAT_MSVC_STATIC_CRT OFF CACHE BOOL "" FORCE)
 add_subdirectory("${ARCHMI_EXPAT_SOURCE}" "${CMAKE_CURRENT_BINARY_DIR}/expat")
 set_target_properties(expat PROPERTIES OUTPUT_NAME archmi_expat RELEASE_POSTFIX "" DEBUG_POSTFIX "" RELWITHDEBINFO_POSTFIX "" MINSIZEREL_POSTFIX "")
 if(EMSCRIPTEN)
  target_compile_options(expat PRIVATE -pthread -fexceptions)
 endif()
endif()
