import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import {M,client,operation,raster,rasterState,setLive,controlFor,noOwned} from '../product-app/harness.mjs';
import {createProductSourceContexts} from '../../src/integration/product-source-contexts.mjs';
import {SourceOperations} from '../../src/app/sources.mjs';
import {createSourceContext} from '../../src/app/source-approval.mjs';
import {sha256,canonicalJSON} from '../../src/storage/common.mjs';
import {encodeRasterPNG} from '../../src/core/png-encode.mjs';
const versions={mechanicsAbi:M._arch_mech_abi_version(),mechanicsSemantics:M._arch_mech_semantics_version(),sourceAbi:M._arch_source_abi_version(),sourceSemantics:M._arch_source_semantics_version(),datumExtension:M._arch_mech_source_datum_extension_version()};
client.serviceCapabilities={geometryVersions:versions};
test('actual edited raster graph proposes durable rebind; retained identity and user overrides are preserved',async()=>{
 const f=await rasterState(),assets=new Map(f.assets);let state=structuredClone(f.state),source=state.content.app.source;
 delete source.metadata.productBindings;state.content.app.source=null;state.content.app.materials=[];state.content.app.materialDefaults=[];state.sourceKind='none';state.revision--;
 let live;const sync=()=>{live={sessionKey:'test-session-1',state,userId:'user-a',projectId:'project-persistent',assetsMap:assets};setLive(live);};sync();
 const bridge=createProductSourceContexts({frameTransport:'product-context-bundle/2',kernel:{operation,ensureRuntime:async()=>client},sources:{source:raster.source,raster:raster.source},context:()=>live});
 const c=controlFor(state),first=await bridge.prepareAdoption({...c,state,source,assets,sourceContext:source.metadata.sourceContext,purpose:'source',operation:'import',materials:[],materialDefaults:[]});
 source.metadata.productBindings=structuredClone(first.productBindings);state=structuredClone(state);state.revision++;state.sourceKind='raster';state.content.app.source=source;
 state.content.app.materials=structuredClone(first.materials);state.content.app.materialDefaults=structuredClone(first.materialDefaults);
 const oldBindings=structuredClone(first.productBindings),overridden=state.content.app.materials.find(m=>m.id===oldBindings.regions[0].materialId);overridden.overridden=true;overridden.label='User western region';
 const edited=assets.get(source.raster.rgba).slice();
 for(let y=0;y<source.raster.height;y++)for(let x=19;x<=20;x++)edited.fill(0,4*(y*source.raster.width+x),4*(y*source.raster.width+x+1));
 const rgbaHash=await sha256(edited),png=await encodeRasterPNG({width:source.raster.width,height:source.raster.height,data:new Uint8ClampedArray(edited)}),pngHash=await sha256(png);
 assets.set(rgbaHash,edited);assets.set(pngHash,png);source.raster.rgba=rgbaHash;source.raster.preview=pngHash;source.assetHashes=[...new Set([...source.assetHashes,rgbaHash,pngHash])];state.revision++;sync();
 const control={...controlFor(state),sourceContext:createSourceContext('convert',source)},before=canonicalJSON(state);
 const reply=await bridge.source.convert({...control,state,source,assets,target:'raster'});assert.equal(reply.status,'proposal');
 const r=reply.result,writer=new SourceOperations(),records=new Map();
 for(const [h,bytes]of assets)await writer.addAsset(bytes,h===source.raw.hash?'source':'derived',records);
 for(const a of r.assets)await writer.addAsset(a.bytes,a.kind,records);
 const descriptor=await writer.rasterDescriptor(r.raster,records);for(const [h,record]of records)assets.set(h,record.bytes);
 const candidate={...structuredClone(source),id:control.sourceContext.id,revision:control.sourceContext.revision,metadata:r.metadata,raster:descriptor,assetHashes:[...records.keys()]};
 const request={...control,state,source:candidate,assets,purpose:'source',operation:'convert',materials:r.materials,materialDefaults:r.materials};
 const plan=await bridge.prepareAdoptionPlan(request);
 assert.equal(plan.status,'proposal');const rebind=plan.proposals.find(p=>p.kind==='source-identity-rebind');assert.ok(rebind);
 assert.equal(rebind.retained.length,1);assert.equal(rebind.allocated.length,2);assert.equal(rebind.retired.length,1);
 assert.equal(rebind.retained[0].sourceKey,oldBindings.regions[1].sourceKey);
 const kept=plan.materials.find(m=>m.id===overridden.id);assert.equal(kept.label,'User western region');assert.equal(kept.overridden,true);assert.equal(kept.product.active,false);
 await assert.rejects(bridge.prepareAdoption(request),{code:'PRODUCT_ADOPTION_DECISION_REQUIRED'});
 assert.equal(canonicalJSON(state),before);assert.equal(state.content.app.source.metadata.productBindings.sourceRevision,0);
 fs.writeFileSync(path.join(process.env.PROJECT_REVIEW_RUN,'evidence/raster-rebind-final.json'),JSON.stringify({versions,sourceHash:source.raw.hash,previousPreparation:source.metadata.rasterPreparation.approvalHash,candidatePreparation:r.metadata.rasterPreparation.approvalHash,plan,noConsentOrDomainCommit:true},null,2));
 bridge.reset();await raster.reset();noOwned();
});
