import {zipSync} from 'fflate';
import {XMLSerializer} from '@xmldom/xmldom';
import {readZip,parseXml,CORE} from './zip-inspect.mjs';
import {check,utf8} from './contracts.mjs';
// Exact-version Bambu/Orca consumers compare the metadata QName as a string.
// lib3mf assigns "customXMLNS0"; adapt only the vendor QName, keeping Core geometry,
// resources, build and relationships generated by lib3mf. Revalidate after this step.
export function finalizeProjectPackage(bytes,adapter){
 const entries=readZip(bytes),path='3D/3dmodel.model',doc=parseXml(entries.get(path)),root=doc.documentElement;
 let found=0;
 for(const m of Array.from(root.getElementsByTagNameNS(CORE,'metadata'))){
  const name=m.getAttribute('name'),[prefix,local]=name.split(':');
  if(local==='Version3mf'&&root.lookupNamespaceURI(prefix)===adapter.namespace){
   m.setAttribute('name','bamboo_slicer:Version3mf');found++;
  }
 }
 check(found===1,'VENDOR_VERSION_METADATA');
 root.setAttributeNS('http://www.w3.org/2000/xmlns/','xmlns:bamboo_slicer',adapter.namespace);
 entries.set(path,utf8.encode(new XMLSerializer().serializeToString(doc)));
 const types=parseXml(entries.get('[Content_Types].xml'));
 for(const node of Array.from(types.getElementsByTagName('Default')))
  if(node.getAttribute('Extension')==='config')node.setAttribute('ContentType','application/octet-stream');
 entries.set('[Content_Types].xml',utf8.encode(new XMLSerializer().serializeToString(types)));
 return zipSync(Object.fromEntries(entries),{level:6});
}
